# Назва для GitHub
name: MacroMenu

# Запуск
on:
  push:
    branches: [ "main" ] # Запускати при пуші в гілку 'main'
  pull_request:
    branches: [ "main" ] # Запускати при створенні Pull Request до гілки 'main'

# Визначення завдань (jobs)
jobs:
  build: # Назва
    runs-on: ubuntu-latest # Виконувати на віртуальній машині Ubuntu

    steps:
      # Крок 1: Перевірка коду з репозиторію
      - name: Checkout Repository
        uses: actions/checkout@v4 # Використовувати офіційний action для checkout коду

      # Крок 2: Налаштування Java Development Kit (JDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Використовувати офіційний action для налаштування Java
        with:
          java-version: '17' # Версія Java, яка потрібна для Minecraft та Forge
          distribution: 'temurin' # Рекомендований дистрибутив JDK
          cache: 'gradle' # Кешувати залежності Gradle для швидших збірок

      # Крок 3: Надання прав на виконання Gradle Wrapper
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Крок 4: Запуск збірки Gradle (build)
      - name: Build with Gradle
        run: ./gradlew build # Запуск Gradle через Wrapper

      # Крок 5: Завантаження артефактів збірки (Необов'язково)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macromenu-build-artifacts # Назва артефакту
          path: build/libs/*.jar # Шлях до .jar файлу після збірки
          retention-days: 7 # Зберігати артефакти 7 днів